### PR TITLE
fix conditions when conditions contain index key

### PR DESCRIPTION
**Pull request by vanquang9387**
Take a look at this comment
https://github.com/baopham/laravel-dynamodb/issues/35#issuecomment-262713695

---
This change is [Reviewable](https://reviewable.io/reviews/baopham/laravel-dynamodb/36)

### CODE REVIEW

**Comment by baopham** [comment]
Nice! I'm going to add tests for this.

**Comment by baopham** [comment]
Thanks!

**Comment by vanquang9387** [comment]
@baopham: please check carefully. I don't have much experience with
DynamoDB and didn't test with any cases other than that mentioned before.

Thank you.

**Comment by baopham** [comment]
Yep. I added the test here https://github.com/baopham/laravel-dynamodb/commit/c70d778a4e12d56f4612bd6ea985d660f27372d7

All tests passed so far.

**Pull request merged**
