### PR TITLE
config testing

### PR DESCRIPTION
**Pull request by ironhoang**
This for circle CI testing

---
This change is [Reviewable](https://reviewable.io/reviews/baopham/laravel-dynamodb/49)

### CODE REVIEW

**Comment by baopham** [comment]
?

**Comment by ironhoang** [comment]
I config same aws key and secret key
When I try run circleCI testing, it alway failed, because
`$region = App::environment() == 'testing' ? 'test' : 'stub';

            $config = [
                'credentials' => [
                    'key' => 'dynamodb_local',
                    'secret' => 'secret',
                ],
                'region' => $region,
                'version' => '2012-08-10',
                'endpoint' => config('services.dynamodb.local_endpoint'),
            ];`
I can not set key for testing.

**Comment by baopham** [comment]
Sorry, I don't fully understand your situation. Are you trying to connect to real AWS service in your CI and because the environment is 'testing' so it is not using the real key and secret?

If I understand you correctly then it can be solved by overriding the service provider with your own logic. 

Normally, we assume not having to connect to third party services during testing, hence the logic OR. 

I'm not super convinced that we need to change the condition to what you proposed. Besides, this will require other changes like the line

```
$region = App::environment() == 'testing' ? 'test' : 'stub';
```
since you change the condition, this line will need to change too.

**Comment by baopham** [comment]
I'm closing this. Let me know if you have any other changes.

**Pull request closed without merging**
