### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 10.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-dynamodb.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "baopham/dynamodb": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Review by nelson6e65 — APPROVED** [review]

**Comment by atymic** [comment]
@baopham any chance of a merge?

**Comment by nelson6e65** [comment]
There are no automatic tests yet, @atymic. Sorry, I was busy, u.u. I'll check my test suite improvements this weekend to accelerate any new implementation. 

But, I'm about to test it manually in a project. You can also give it a try temporally by modifying the branch in your composer.json:

```jsonc
{
    "require": {
        // other packages
        "baopham/dynamodb": "dev-l10-compatibility",
    }
}
```

**Comment by nelson6e65** [comment]
@atymic let me see if I can make a pre-release. I'll check this later when I get home.

**Comment by nelson6e65** [comment]
@atymic Can you install and check if any problem in new [`v6.3.0` release](https://github.com/baopham/laravel-dynamodb/releases/tag/6.3.0)?

**Pull request merged**
