### PR TITLE
Local DB when local_endpoint is defined in .env

### PR DESCRIPTION
**Pull request by gregorskii**
Adds support for #2

### CODE REVIEW

**Comment by baopham** [comment]
Thanks.

But it should already be done here: https://github.com/baopham/laravel-dynamodb/blob/2c7ddaa14b2fde4cdd746373adebe3796f2b351c/src/DynamoDbServiceProvider.php#L23

If you define in your `config/services.php` like below, it should work

```
'dynamodb' => [
    //...
    'local' => env('DYNAMODB_LOCAL', true)
],
```
Except that that DB file will need to be named as `dynamodb_local_stub.db` (https://github.com/baopham/laravel-dynamodb/blob/2c7ddaa14b2fde4cdd746373adebe3796f2b351c/src/DynamoDbServiceProvider.php#L25)

Can you see if this work?

**Comment by gregorskii** [comment]
I did see that field, set it to true and it did not work.

It may be because the value from the confit is a string, it would likely need to evaluate it as a Boolean.

**Comment by baopham** [comment]
did you use `env()` or `getenv()`? `env()` will convert a `'true'` string to `true`

**Comment by gregorskii** [comment]
Ok will try tomorrow. Thank you.

**Comment by gregorskii** [comment]
Yes this worked. I think I had the services array named wrong at first.

Thanks!

**Pull request closed without merging**
