### PR TITLE
Changed version system for Laravel 6

### PR DESCRIPTION
**Pull request by guspio**
With the old version of composer.json file, Laravel updates were blocked at version 6.0.4 whereas currently the last one is 6.13. This Pull Request allows to overcome this problem.

### CODE REVIEW

**Comment by baopham** [comment]
thank you

**Comment by Ciaro** [comment]
@baopham  Could you make a new version tag for this? Thanks!

**Comment by baopham** [comment]
@Ciaro yep, I'll do that later today. Sorry about that

**Comment by baopham** [comment]
@Ciaro done: v5.0.1 or v6.0.0 if you want Laravel 7 support

**Comment by Ciaro** [comment]
@baopham perfect: thank you! :)

**Pull request merged**
