### PR TITLE
Laravel 6.0 Support

### PR DESCRIPTION
**Pull request by dp88**
I've updated `composer.json` to include support for Laravel 6.0. The other change that needed addressing is that Laravel 6 removes the `str_*` and `array_*` helper functions in favor of accessing those methods via `Illuminate\Support\Str` and `Illuminate\Support\Arr` respectively.

edit: I've also confirmed that all tests still pass going back to Laravel 5.3.

### CODE REVIEW

**Comment by BenSampo** [comment]
Re broken tests on PHP 7.1, from the Laravel 6 upgrade notes:

"PHP 7.1 will no longer be actively maintained as of December 2019. Therefore, Laravel 6.0 requires PHP 7.2 or greater."

**Comment by reececomo** [comment]
What's the next step here?

If you want, we can signal to Travis to skip the PHP 7.1 step on Laravel 6.0 builds?

**Comment by dp88** [comment]
> Re broken tests on PHP 7.1, from the Laravel 6 upgrade notes:
>
> "PHP 7.1 will no longer be actively maintained as of December 2019. Therefore, Laravel 6.0 requires PHP 7.2 or greater."

> If you want, we can signal to Travis to skip the PHP 7.1 step on Laravel 6.0 builds?

I think it makes sense to drop the PHP 7.1 step from Travis altogether.

@baopham what's your preference? Are you available to review and merge this PR?

**Comment by reececomo** [comment]
Given that PHP 7.1 to 7.2 is such a minor upgrade, I think that makes sense @dp88.

You can still install a functioning Laravel 5.x version of `baopham/laravel-dynamodb` through the tagged versions.

**Comment by reececomo** [comment]
@baopham Any chance of a merge here?

You could create a `laravel-5-*` branch and have `master` be for the latest version of laravel? 😄

**Comment by crynobone** [comment]
Anyone maintaining a temporary fork with Laravel 6 support.

**Comment by dp88** [comment]
I have a working Laravel 6 branch on my own fork, but I can't commit to maintaining it long term:
https://github.com/stechstudio/laravel-dynamodb/tree/dev-master

**Comment by reececomo** [comment]
@baopham still active or?

**Comment by gilbertronaldo** [comment]
@baopham hello?

**Comment by lamungu** [comment]
@baopham Would be great to know if this would also be available for Laravel 6.x onwards. The framework is already at 6.5 and this repo has yet to be updated

**Comment by Kovalchuk91** [comment]
@baopham Can you please update what's the status of this repo. Waiting for 6.* support also

**Comment by reececomo** [comment]
@baopham we’re at 6.7 already

**Comment by JackPriceBurns** [comment]
@reececomo @Kovalchuk91 @lamungu @gilbertronaldo @dp88 maybe it would be best if one of us forks the package and starts maintaining it, this repo doesn't appear to be active anymore and 6.x support is a must, Laravel 6 has been out for a while now.

I would be willing to help maintain or just maintain it myself and improve the package in a few places.

**Comment by reececomo** [comment]
@JackPriceBurns @Kovalchuk91 @lamungu @gilbertronaldo @dp88 I'm down for that.

Maybe `/laravel-dynamo` or `/laradynamodb` is available?

We should let @dp88 do it so he can get the delicious open source credit. Otherwise I've created us a new laravel team in the `HubrioAU` organisation if you're happy to put it there

**Comment by reececomo** [comment]
Have created a Laravel 6 fork in the meantime (and added everyone mentioned as project maintainers) to: https://github.com/hubrioAU/laravel-dynamodb

Otherwise if @dp88 wants to make it, I say we move to his.

**Comment by crynobone** [comment]
There https://github.com/rennokki/dynamodb

I also made a fork via https://github.com/laravie/eloquent-dynamodb but does require namespace rename

**Comment by JackPriceBurns** [comment]
I like the idea of having an organisation and us all work on it there, we now have 3 repos + the original + dp88's repo to work with, so we should come to a consensus as to which to use.

**Comment by baopham** [comment]
Hey, sorry all. I was completely away.

**Comment by baopham** [comment]
If anyone is interested in maintaining this repo, let me know #213!

**Comment by baopham** [comment]
Release with tag v5.0.0

**Comment by BenSampo** [comment]
Thanks @baopham 👍

**Comment by dp88** [comment]
I'm afraid I don't have the bandwidth to maintain a fork at this time. Thanks for merging though, @baopham.

**Comment by reececomo** [comment]
All good, I'd say continue to work on this here 👍

Thanks for merging @baopham -- @JackPriceBurns @dp88 might be worth adding yourselves as maintainers

**Pull request merged**
